language: python
python:
  - "3.7"

dist: bionic

jobs:
  include:
    - stage: test
      name: PyTest-GUI
      before_script:
        - python -m pip install --upgrade pip
        - pip install -r ./requirement.txt
      script: 
        - pytest -s -v ./GUI_test.py
      addons:
        apt:
          packages:
            - libxkbcommon-x11-0
      services:
        - xvfb
